[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -std=c++17
    -fstack-protector-all
    -O2
lib_ldf_mode = chain+
upload_speed = 921600
